import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
import matplotlib as mpl
import re
from matplotlib.ticker import AutoMinorLocator


rc('text', usetex=True)
rc('font', size=15)
rc('legend', fontsize=13)
rc('text.latex')

def readOutcar(outcarfile='OUTCAR', kpointsfile='KPOINTS'):
    """Obtain the band energies from OUTCAR file generated by VASP.

    Args:
        outcarfile (str, optional): Path to OUTCAR file. Defaults to 'OUTCAR'.
        kpointsfile (str, optional): Path to KPOINTS file. Defaults to 'KPOINTS'.
    """
    # Separate outcar file in lines and remove trailing and heading whitespaces
    outcar = [line for line in open(outcarfile) if line.strip()] 
    
    for i, line in enumerate(outcar):
        # Check for needed constant values and parameters
        if 'NKPTS =' in line:
            nkpts = int(line.split()[3])
            nband = int(line.split()[-1])
            
        if 'ISPIN  =' in line:
            ispin = int(line.split()[2])
        
        if "k-points in reciprocal lattice and weights" in line:
            Lvkpts = i + 1

        if 'reciprocal lattice vectors' in line:
            ibasis = i + 1

        if 'E-fermi' in line:
            efermi = float(line.split()[2])
            LineEfermi = i + 1
            

        if 'NELECT' in line:
            nelect = float(line.split()[2])
      
    # Get basis.       
    # When the supercell is too large, spaces are missing between real space
    # lattice constants. A bug found out by Wei Xie (weixie4@gmail.com) and
    # code provided by Irián ¿Sánchez?
    B = np.array([line.split()[-3:] for line in outcar[ibasis:ibasis+3]],
                 dtype=float)
    
    # k-points vectors and weights
    dummy = np.array([line.split() for line in outcar[Lvkpts:Lvkpts+nkpts]],
                   dtype=float)
    vkpts = dummy[:, :3]
    wkpts = dummy[:, -1]
    
    # Check how many lines contain information about the bands
    # For ispin = 2, there are two extra lines "spin component..."
    N = (nband + 2) * nkpts * ispin + (ispin - 1) * 2
    bands = []
    filledfactor = []
    
    for line in outcar[LineEfermi:LineEfermi + N]:
        # Skip non-relevant lines
        if 'spin component' in line or 'band No.' in line:
            continue
        if 'k-point' in line:
            continue
        bands.append(float(line.split()[1]))
        filledfactor.append(float(line.split()[2]))
        
    bands = np.array(bands, dtype=float).reshape((ispin, nkpts, nband))
    filledfactor = np.array(filledfactor, dtype=float).reshape((ispin, nkpts, nband))
    
    kp = open(kpointsfile).readlines()
    
    if kp[2][0].upper() == 'L':
        Nk_in_seg = int(kp[1].split()[0]) # Number of k-points per line
        Nseg = nkpts // Nk_in_seg # Number of lines
        vkpt_diff = np.zeros_like(vkpts, dtype=float)

        for ii in range(Nseg):
            start = ii * Nk_in_seg
            end = (ii + 1) * Nk_in_seg
            vkpt_diff[start:end, :] = vkpts[start:end, :] - vkpts[start, :]

        kpt_path = np.linalg.norm(np.dot(vkpt_diff, B), axis=1)
        
        for ii in range(1, Nseg):
            start = ii * Nk_in_seg
            end = (ii + 1) * Nk_in_seg
            kpt_path[start:end] += kpt_path[start-1]

        
        kpt_bounds = np.concatenate((kpt_path[0::Nk_in_seg], [kpt_path[-1], ]))

    return kpt_path, bands, efermi, kpt_bounds, wkpts, nelect, filledfactor


def bandplot(kpath, bands, efermi, kpt_bounds, nelect, kpointsfile =  "KPOINTS",fig_size = (15,8),filledvsempty=False,filledfactor = None,e_window = None,line_w = 0.5,fig_name = "bands.pdf",fig_title=None):
    """Plot Band Structure using matplotlib

    Args:
        kpath: Array of kpoints.
        bands: Array of energy values for each kpoint.
        efermi: Fermi energy.
        kpt_bounds: Values of high-symmetry points.
        nelect: Number ofelectrons
        kpointsfile: Path to KPOINTS file. Defaults to 'KPOINTS'. Defaults to "KPOINTS".
        fig_size: Size of matplotlib figure. Defaults to (15,8).
        filledvsempty: Wether to plot filled bands blue and empty bands red. If True, a filledfactor variable must be provided. Defaults to False.
        filledfactor: Occupation coeficient for each band and each kpoint. Defaults to None.
        e_window: Energy window for the plot (yaxis limits). Defaults to None.
        line_w: Line width for the plot. Defaults to 0.5.
        fig_name: Name for the figure file. Defaults to "bands.pdf".
        fig_title: Title of the matplotlib figure. Defaults to None.
    """
    
    width, height = fig_size
    
    if e_window != None:
        ymin, ymax = e_window[0], e_window[1]
    else:
        ymin, ymax = -4.0,4.0
        
    fig = plt.figure()
    fig.set_size_inches(width, height)
    ax = plt.subplot(111)
    
    nspin, nkpts, nbands = bands.shape
    
    clrs = ['r', 'b']
    
    for Ispin in range(nspin):
        for Iband in range(nbands):
            color = 'k'
            if filledvsempty and filledfactor is not None:
                if filledfactor[Ispin, 0,Iband].any() == 1.:
                    color = 'b'
                if filledfactor[Ispin, 0,Iband].any() == 0.:
                    color = 'r'

            if float(Iband) >= nelect:
                line, = ax.plot(kpath, bands[Ispin, :, Iband], lw=line_w, zorder=0,
                                alpha=0.8, color=color)
            else:
                line, = ax.plot(kpath, bands[Ispin, :, Iband], lw=line_w, zorder=0,
                                alpha=0.8, color=color)
    
    # add extra horizontal/vertical lines
    
    for bd in kpt_bounds:
        ax.axvline(x=bd, ls='-', color='k', lw=0.5, alpha=0.5)
        
    ax.set_ylabel('$E - E_f$ [eV]',  # fontsize='small',
                  labelpad=5)
    ax.set_ylim(ymin, ymax)
    ax.set_xlim(kpath.min(), kpath.max())
    
    ax.set_xticks(kpt_bounds)
    
    # Read and use KPOINTS file for tick labels.

    with open(kpointsfile,'r') as KPointsFile:
        TmpFlag = 0;
        TmpLabels = [];
        for TmpLine in KPointsFile:
            TmpLine = TmpLine.strip()
            if TmpFlag == 1:                    
                TmpLine = re.sub(r'^.*\!\s?', '', TmpLine)
                TmpLine.strip()
                if TmpLine != "":
                    if TmpLine == "G" or TmpLine == "Gamma" or TmpLine == "GM":
                        TmpLabels.append(r'$\mathrm{{\mathsf{\Gamma}}}$')
                    else:
                        TmpLabels.append(r'$\mathrm{\mathsf{'+TmpLine+'}}$')
            if (TmpLine == "reciprocal") | (TmpLine == "rec"):
                TmpFlag = 1
        TmpLabels2 = [TmpLabels[0]]
        TmpIndex = 1
        while TmpIndex < (len(TmpLabels) - 1):
            if TmpLabels[TmpIndex + 1] == TmpLabels[TmpIndex]:
                TmpLabels2.append(TmpLabels[TmpIndex])
            else:
                TmpLabels2.append(TmpLabels[TmpIndex]+'|'+TmpLabels[TmpIndex + 1])
            TmpIndex += 2
        
        TmpLabels2.append(TmpLabels[len(TmpLabels) - 1])
        ax.set_xticklabels(TmpLabels2)
        
        ax.yaxis.set_minor_locator(AutoMinorLocator(2))
        ax.axhline(y=0, xmin=0, xmax=1, linestyle='dotted', color='black', linewidth=0.5)
        ax.set_title(fig_title)
        plt.tight_layout(pad=0.20)
        plt.savefig(fig_name)
        plt.show()
        return kpath, bands


    
def plot_bands_from_VASP(outcarfile = "OUTCAR", kpointsfile = "KPOINTS",fig_size = (10,7.5),ewindow =  None,filledvsempty=False,fig_name = "bands.pdf",fig_title=None,efermi=None):
    """ Plot the band structure from KPOINTS and OUTCAR files.

    Args:
        outcarfile (str, optional): Path to OUTCAR file. Defaults to 'OUTCAR'.
        kpointsfile (str, optional): Path to KPOINTS file. Defaults to 'KPOINTS'.
        fig_size: Size of matplotlib figure. Defaults to (10,7.5).
        e_window: Energy window for the plot (yaxis limits). Defaults to None.
        filledvsempty: Wether to plot filled bands blue and empty bands red. Defaults to False.
        fig_name: Name for the figure file. Defaults to "bands.pdf".
        fig_title: Title of the matplotlib figure. Defaults to None.
        efermi: Fermi energy if previously known.. Defaults to None.
    """
    
    # Use non-interactive backend in case there is no display
    mpl.use('agg')
    mpl.rcParams['axes.unicode_minus'] = False
    
    kpath, bands, efermi_, kpt_bounds, wkpts, nelect, filledfactor = readOutcar(outcarfile,kpointsfile)
    
    if efermi == None:
        efermi = efermi_
    
    
    if filledvsempty:
        bandplot(kpath, bands-efermi, efermi,kpt_bounds, nelect,kpointsfile=kpointsfile, e_window=ewindow, fig_size=fig_size, fig_name=fig_name,fig_title=fig_title, filledvsempty=filledvsempty, filledfactor=filledfactor)
    else:
        bandplot(kpath, bands-efermi, efermi,kpt_bounds, nelect,kpointsfile=kpointsfile, e_window=ewindow, fig_size=fig_size, fig_name=fig_name,fig_title=fig_title)
        


plot_bands_from_VASP(outcarfile="Ag2Te\MBJ_thirdtry\OUTCAR", kpointsfile="Ag2Te\MBJ_thirdtry\KPOINTS",fig_name = "Ag2Te\\bands_mbjthirdtry_newcode.pdf", ewindow=[-1,1], filledvsempty=True)